var s_wid = 0;
var line_1 = "";
var line_2 = "";
var line_3 = "";
var line_4 = "";
var line_5 = "";
var line_6 = "";
var line_7 = "";
var line_height = 18;

draw_set_font(fnt_title);
draw_set_color(c_aqua);
draw_set_halign(fa_center);
draw_set_valign(fa_middle);
draw_text(room_width * .5, 32, "8 Direction Walking Controls - Room 4");
draw_set_color(c_white);
draw_set_font(fnt_reg);
draw_text(room_width * .5, 67, "Max Turn Rate on player and animated between frames, please note that this does not affect the speed the player can turn at just the speed of rotation of the sprite\nGamepad not supported");
		turn_rate = 5 * room_speed;
var code_y = 160;
var code_x = 680;
draw_set_halign(fa_left);
draw_set_font(fnt_code);
draw_set_color(c_white);
draw_text(code_x, code_y, "CREATE EVENT");
draw_set_color(c_green);
code_y += 20;
line_1 = "// Maximum number of degrees per frame sprite can rotate at";
draw_text (code_x + s_wid, code_y, line_1);
code_y += 16;
draw_set_color(c_user_var);
line_2 = "turn_rate "
draw_text (code_x + s_wid, code_y, line_2);
draw_set_color(c_white);
line_3 = "= ";
s_wid += string_width(line_2);
draw_text(code_x + s_wid, code_y, line_3);
draw_set_color(c_internal_var);
line_4 = "5 ";
s_wid += string_width(line_3);
draw_text(code_x + s_wid, code_y, line_4);
draw_set_color(c_white);
line_5 = " * ";
s_wid += string_width(line_4);
draw_text(code_x + s_wid, code_y, line_5);
draw_set_color(c_lime);
line_6 = "room_speed";
s_wid += string_width(line_5);
draw_text(code_x + s_wid, code_y, line_6);
draw_set_color(c_white);
line_7 = ";";
s_wid += string_width(line_6);
draw_text(code_x + s_wid, code_y, line_7);

code_y += line_height*2;
s_wid = 0;
draw_text(code_x, code_y, "STEP EVENT");
		
code_y += line_height;
draw_set_color(c_green);
line_1 = "// Update player direction";
draw_text(code_x + s_wid, code_y, line_1);

code_y += line_height;
s_wid = 0;
// /if (speed != 0) // Only update direction if moving
draw_set_color(c_user_funct);
line_1 = "if ";
draw_text(code_x + s_wid, code_y, line_1);
draw_set_color(c_white);
s_wid += string_width(line_1);
line_2 = "(";
draw_text(code_x + s_wid, code_y, line_2);
draw_set_color(c_lime);
s_wid += string_width(line_2);
line_3 = "speed ";
draw_text(code_x + s_wid, code_y, line_3);
draw_set_color(c_white);
s_wid += string_width(line_3);
line_4 = "!= ";
draw_text(code_x + s_wid, code_y, line_4);
draw_set_color(c_internal_var);
s_wid += string_width(line_4);
line_5 = "0";
draw_text(code_x + s_wid, code_y, line_5);
draw_set_color(c_white);
s_wid += string_width(line_5);
line_6 = ")";
draw_text(code_x + s_wid, code_y, line_6);
draw_set_color(c_green);
s_wid += string_width(line_6);
line_7 = " //  Only update direction if moving";
draw_text(code_x + s_wid, code_y, line_7);

code_y += line_height;
s_wid = 0;
// { 
draw_set_color(c_white);
line_1 = "{";
draw_text(code_x + s_wid, code_y, line_1);

code_y += line_height;
s_wid = 0;
draw_set_color(c_green);
line_1 = "   // Animate between angles if there is a change";
draw_text(code_x + s_wid, code_y, line_1);

code_y += line_height;
s_wid = 0;
//if (image_angle != direction) 
draw_set_color(c_user_funct);
line_1 = "   if ";
draw_text(code_x + s_wid, code_y, line_1);
s_wid += string_width(line_1);
draw_set_color(c_white);
line_2 = "(";
draw_text(code_x + s_wid, code_y, line_2);
s_wid += string_width(line_2);
draw_set_color(c_lime);
line_3 = "image_angle ";
draw_text(code_x + s_wid, code_y, line_3);
s_wid += string_width(line_3);
draw_set_color(c_white);
line_4 = "!= ";
draw_text(code_x + s_wid, code_y, line_4);
s_wid += string_width(line_4);
draw_set_color(c_lime);
line_5 = "direction";
draw_text(code_x + s_wid, code_y, line_5);
s_wid += string_width(line_5);
draw_set_color(c_white);
line_6 = ")";
draw_text(code_x + s_wid, code_y, line_6);

code_y += line_height;
s_wid = 0;
// { 
draw_set_color(c_white);
line_1 = "   {";
draw_text(code_x + s_wid, code_y, line_1);

code_y += line_height;
s_wid = 0;
draw_set_color(c_green);
line_1 = "     // Get angle difference in degrees between -180 and 180";
draw_text(code_x + s_wid, code_y, line_1);

code_y += line_height;
s_wid = 0;
draw_set_color(c_green);
line_1 = "     //     between image_angle and direction";
draw_text(code_x + s_wid, code_y, line_1);
		
//var new_ang = angle_difference(image_angle, direction);
code_y += line_height;
s_wid = 0; 
draw_set_color(c_user_funct);
line_1 = "     var ";
draw_text(code_x + s_wid, code_y, line_1);
s_wid += string_width(line_1);
draw_set_color(c_user_var);
line_2 = "new_ang";
draw_text(code_x + s_wid, code_y, line_2);
s_wid += string_width(line_2);
draw_set_color(c_white);
line_3 = " = ";
draw_text(code_x + s_wid, code_y, line_3);
s_wid += string_width(line_3);
draw_set_color(c_user_funct);
line_4 = " angle_difference";
draw_text(code_x + s_wid, code_y, line_4);
s_wid += string_width(line_4);
draw_set_color(c_white);
line_5 = "(";
draw_text(code_x + s_wid, code_y, line_5);
s_wid += string_width(line_5);
draw_set_color(c_lime);
line_6 = "image_angle";
draw_text(code_x + s_wid, code_y, line_6);
s_wid += string_width(line_6);
draw_set_color(c_white);
line_7 = ", ";
draw_text(code_x + s_wid, code_y, line_7);
s_wid += string_width(line_7);
draw_set_color(c_lime);
line_1 = "direction";
draw_text(code_x + s_wid, code_y, line_1);
s_wid += string_width(line_1);
draw_set_color(c_white);
line_2 = ");";
draw_text(code_x + s_wid, code_y, line_2);

code_y += line_height * 2;
s_wid = 0;
draw_set_color(c_green);
line_1 = "     // Takes the smaller of the two the angle or the maximum";
draw_text(code_x + s_wid, code_y, line_1);

code_y += line_height;
s_wid = 0;
draw_set_color(c_green);
line_1 = "     // turn_rate and multiplies by the the sign of the angle";
draw_text(code_x + s_wid, code_y, line_1);

//image_angle -= min(abs(new_ang), turn_rate * tick) * sign(new_ang);
code_y += line_height;
s_wid = 0; 
draw_set_color(c_lime);
line_1 = "       image_angle";
draw_text(code_x + s_wid, code_y, line_1);
s_wid += string_width(line_1);
draw_set_color(c_white);
line_2 = "-=";
draw_text(code_x + s_wid, code_y, line_2);
s_wid += string_width(line_2);
draw_set_color(c_user_funct);
line_3 = "min";
draw_text(code_x + s_wid, code_y, line_3);
s_wid += string_width(line_3);
draw_set_color(c_white);
line_4 = "(";
draw_text(code_x + s_wid, code_y, line_4);
s_wid += string_width(line_4);
draw_set_color(c_user_funct);
line_5 = "abs";
draw_text(code_x + s_wid, code_y, line_5);
s_wid += string_width(line_5);
draw_set_color(c_white);
line_6 = "(";
draw_text(code_x + s_wid, code_y, line_6);
s_wid += string_width(line_6);
draw_set_color(c_user_var);
line_7 = "new_ang";
draw_text(code_x + s_wid, code_y, line_7);
s_wid += string_width(line_7);
draw_set_color(c_white);
line_1 = "),";
draw_text(code_x + s_wid, code_y, line_1);
s_wid += string_width(line_1);
draw_set_color(c_user_var);
line_2 = "turn_rate";
draw_text(code_x + s_wid, code_y, line_2);
s_wid += string_width(line_2);
draw_set_color(c_white);
line_3 = "*";
draw_text(code_x + s_wid, code_y, line_3);
s_wid += string_width(line_3);
draw_set_color(c_user_var);
line_4 = "tick";
draw_text(code_x + s_wid, code_y, line_4);
s_wid += string_width(line_4);
draw_set_color(c_white);
line_5 = ")*";
draw_text(code_x + s_wid, code_y, line_5);
s_wid += string_width(line_5);
draw_set_color(c_user_funct);
line_6 = "sign";
draw_text(code_x + s_wid, code_y, line_6);
s_wid += string_width(line_6);
draw_set_color(c_white);
line_7 = "(";
draw_text(code_x + s_wid, code_y, line_7);
s_wid += string_width(line_7);
draw_set_color(c_user_var);
line_1 = "new_ang";
draw_text(code_x + s_wid, code_y, line_1);
s_wid += string_width(line_1);
draw_set_color(c_white);
line_2 = ");";
draw_text(code_x + s_wid, code_y, line_2);

code_y += line_height;
s_wid = 0;
draw_set_color(c_green);
line_1 = "     // Adds new angle and keeps between 0 and 359";
draw_text(code_x + s_wid, code_y, line_1);
		
//image_angle = image_angle mod(360); 
code_y += line_height;
s_wid = 0; 
draw_set_color(c_lime);
line_1 = "       image_angle";
draw_text(code_x + s_wid, code_y, line_1);
s_wid += string_width(line_1);
draw_set_color(c_white);
line_2 = " = ";
draw_text(code_x + s_wid, code_y, line_2);
s_wid += string_width(line_2);
draw_set_color(c_lime);
line_3 = "image_angle ";
draw_text(code_x + s_wid, code_y, line_3);
s_wid += string_width(line_3);
draw_set_color(c_user_funct);
line_4 = "mod";
draw_text(code_x + s_wid, code_y, line_4);
s_wid += string_width(line_4);
draw_set_color(c_white);
line_7 = "(";
draw_text(code_x + s_wid, code_y, line_7);
s_wid += string_width(line_7);
draw_set_color(c_internal_var);
line_5 = "360";
draw_text(code_x + s_wid, code_y, line_5);
s_wid += string_width(line_5);
draw_set_color(c_white);
line_2 = ");";
draw_text(code_x + s_wid, code_y, line_2);

//	}
code_y += line_height;
s_wid = 0;
draw_set_color(c_white);
line_1 = "   }";
draw_text(code_x + s_wid, code_y, line_1);

code_y += line_height;
s_wid = 0;
draw_set_color(c_lime);
line_1 = "   sprite_index";
draw_text(code_x + s_wid, code_y,line_1);
s_wid += string_width(line_1);
draw_set_color(c_white);
line_2 = " = ";
draw_text(code_x + s_wid, code_y,line_2);
s_wid += string_width(line_2);
draw_set_color(c_internal_var);
line_3 = "spr_top_down_symmetric";
draw_text(code_x + s_wid, code_y,line_3);
s_wid += string_width(line_3);
draw_set_color(c_white);
line_4 = ";";
draw_text(code_x + s_wid, code_y,line_4);

//}
code_y += line_height;
s_wid = 0;
draw_set_color(c_white);
line_1 = "}";
draw_text(code_x + s_wid, code_y, line_1);


code_y += line_height;
s_wid = 0;
draw_set_color(c_white);
line_1 = "else";
draw_text(code_x + s_wid, code_y, line_1);

//{
code_y += line_height;
s_wid = 0;
draw_set_color(c_white);
line_1 = "{";
draw_text(code_x + s_wid, code_y, line_1);

code_y += line_height;
s_wid = 0;
draw_set_color(c_lime);
line_1 = "   sprite_index";
draw_text(code_x + s_wid, code_y,line_1);
s_wid += string_width(line_1);
draw_set_color(c_white);
line_2 = " = ";
draw_text(code_x + s_wid, code_y,line_2);
s_wid += string_width(line_2);
draw_set_color(c_internal_var);
line_3 = "spr_top_down_symmetric_idle";
draw_text(code_x + s_wid, code_y,line_3);
s_wid += string_width(line_3);
draw_set_color(c_white);
line_4 = ";";
draw_text(code_x + s_wid, code_y,line_4);
		
//}
code_y += line_height;
s_wid = 0;
draw_set_color(c_white);
line_1 = "}";
draw_text(code_x + s_wid, code_y, line_1);

